trigger:
- main

pool:
  name: 'MTPre'   # Replace with your agent pool name

variables:
  appPoolName: 'CICDTest'
  deployPath: 'E:\Deployedprojects\CICDTest'
  backupPath: 'E:\Deployments\backup\CICDTest'
  publishOutput: '$(Build.ArtifactStagingDirectory)\publish'
  
  # 👇 Add these proxy variables (HTTP and HTTPS)
  HTTP_PROXY: 'http://185.46.212.88:80'
  HTTPS_PROXY: 'http://185.46.212.88:80'
  NO_PROXY: 'localhost,127.0.0.1'  # Optional: Bypass proxy for local addresses

stages:
- stage: Build
  displayName: Build Stage
  jobs:
  - template: build.yml

- stage: Deploy
  displayName: Deploy Stage
  dependsOn: Build
  condition: succeeded()
  jobs:
  - template: deploy.yml

- stage: Rollback
  displayName: Rollback Stage
  dependsOn: Deploy
  condition: failed()
  jobs:
  - template: rollback.yml
