trigger:
- main

pool:
  name: 'MTPre'   # Replace with your agent pool name

variables:
  appPoolName: 'CICDTest'
  deployPath: 'E:\Deployedprojects\CICDTest'
  backupPath: 'E:\Deployments\backup\CICDTest'
  publishOutput: '$(Build.ArtifactStagingDirectory)\publish'

stages:
- stage: Build
  displayName: Build Stage
  jobs:
  - template: build.yml

- stage: Deploy
  displayName: Deploy Stage
  dependsOn: Build
  condition: succeeded()
  jobs:
  - template: deploy.yml

- stage: Rollback
  displayName: Rollback Stage
  dependsOn: Deploy
  condition: failed()
  jobs:
  - template: rollback.yml
