jobs:
- job: BuildJob
  displayName: Build .NET Core Application
  
  #steps:
#  - checkout: self
#    clean: true
    
  steps:
    - task: UseDotNet@2
      inputs:
        packageType: 'sdk'
        version: '8.0.400'

    - task: UseDotNet@2
      inputs:
        packageType: 'sdk'
        version: '6.0.406'

    - task: NuGetCommand@2
      inputs:
        command: 'restore'
        restoreSolution: '**/*.sln'

    - task: DotNetCoreCLI@2
      displayName: Build Project
      inputs:
        command: 'build'
        projects: '**/*.csproj'
        arguments: '--configuration Release'

    - task: DotNetCoreCLI@2
      displayName: Publish Project
      inputs:
        command: 'publish'
        publishWebProjects: true
        arguments: '--configuration Release --output $(publishOutput)'
